# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IFC2CityGML
                                 A QGIS plugin
 Das Plugin konvertiert Gebäudemodelle aus IFC zu CityGML.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-23
        copyright            : (C) 2022 by Nicklas Meyer (Jade Hochschule Oldenburg)
        email                : nicklas.meyer@student.jade-hs.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IFC2CityGML class from file IFC2CityGML.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ifc_to_citygml import IFC2CityGML
    return IFC2CityGML(iface)
